"""Local provider health, usage, budget and routing governance.

The service intentionally keeps user intent (the provider ``enabled`` flag)
separate from operational eligibility.  Secrets never enter this database;
rows are bound to a random credential version generated by the DPAPI vault.
"""

from __future__ import annotations

import hashlib
import json
import math
import threading
import time
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from email.utils import parsedate_to_datetime
from typing import Any, Iterable, Mapping, Optional
from zoneinfo import ZoneInfo

import database


STATES = frozenset({
    "unknown", "healthy", "auth_required", "permission_denied",
    "quota_exhausted", "rate_limited", "model_unavailable", "degraded",
    "unreachable",
})
BLOCKING_STATES = frozenset({
    "auth_required", "quota_exhausted", "permission_denied",
    "model_unavailable",
})
ROUTING_MODES = frozenset({"off", "ask", "auto_within_policy"})
EXPIRY_SOURCES = frozenset({"user_declared", "provider_verified", "unknown"})
_SERVICE: Optional["ModelGovernanceService"] = None


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(value: Optional[datetime] = None) -> str:
    return (value or _now()).astimezone(timezone.utc).isoformat()


def _parse_time(value: Any) -> Optional[datetime]:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return parsed.replace(tzinfo=timezone.utc) if parsed.tzinfo is None else parsed.astimezone(timezone.utc)
    except (TypeError, ValueError):
        return None


def endpoint_fingerprint(endpoint: str) -> str:
    normalized = str(endpoint or "").strip().rstrip("/").casefold()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def _clean_id(value: Any, *, maximum: int = 200) -> str:
    result = str(value or "").strip()
    if not result or len(result) > maximum or any(ord(char) < 32 for char in result):
        raise ValueError("identifier is invalid")
    return result


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def _loads(value: Any, default: Any) -> Any:
    try:
        return json.loads(value) if value else default
    except (TypeError, ValueError):
        return default


def parse_retry_after(value: Any, *, now: Optional[datetime] = None) -> Optional[datetime]:
    text = str(value or "").strip()
    if not text:
        return None
    current = now or _now()
    try:
        seconds = max(0, min(3600, int(float(text))))
        return current + timedelta(seconds=seconds)
    except ValueError:
        try:
            parsed = parsedate_to_datetime(text)
            if parsed.tzinfo is None:
                parsed = parsed.replace(tzinfo=timezone.utc)
            return min(current + timedelta(hours=1), max(current, parsed.astimezone(timezone.utc)))
        except (TypeError, ValueError, OverflowError):
            return None


class GovernanceError(ValueError):
    def __init__(self, code: str, message: str, *, status_code: int = 409, details: Optional[dict[str, Any]] = None):
        super().__init__(message)
        self.code = code
        self.status_code = status_code
        self.details = details or {}


@dataclass(frozen=True)
class GovernanceDecision:
    allowed: bool
    code: str = ""
    message: str = ""
    retry_at: Optional[str] = None
    warnings: tuple[dict[str, Any], ...] = ()
    reservation_id: Optional[str] = None


class ModelGovernanceService:
    def __init__(self, *, database_module: Any = database, clock: Any = _now) -> None:
        self.database = database_module
        self.clock = clock
        self._lock = threading.RLock()

    def initialize(self) -> dict[str, int]:
        with self.database.get_db_conn() as conn:
            conn.executescript(
                """
                CREATE TABLE IF NOT EXISTS provider_credential_metadata (
                    provider_id TEXT PRIMARY KEY,
                    credential_version_id TEXT NOT NULL,
                    expires_at TEXT,
                    expiry_source TEXT NOT NULL DEFAULT 'unknown',
                    never_expires INTEGER NOT NULL DEFAULT 0,
                    last_verified_at TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    CHECK (expiry_source IN ('user_declared','provider_verified','unknown'))
                );
                CREATE TABLE IF NOT EXISTS provider_operational_states (
                    provider_id TEXT NOT NULL,
                    model_id TEXT NOT NULL DEFAULT '',
                    endpoint_sha256 TEXT NOT NULL,
                    credential_version_id TEXT NOT NULL,
                    state TEXT NOT NULL,
                    reason_code TEXT,
                    reason TEXT,
                    last_success_at TEXT,
                    last_failure_at TEXT,
                    failure_streak INTEGER NOT NULL DEFAULT 0,
                    cooldown_until TEXT,
                    retry_at TEXT,
                    half_open_claimed_at TEXT,
                    updated_at TEXT NOT NULL,
                    PRIMARY KEY (provider_id, model_id, endpoint_sha256),
                    CHECK (state IN ('unknown','healthy','auth_required','permission_denied','quota_exhausted','rate_limited','model_unavailable','degraded','unreachable'))
                );
                CREATE TABLE IF NOT EXISTS provider_usage_events (
                    call_id TEXT PRIMARY KEY,
                    run_id TEXT,
                    project_id TEXT,
                    provider_id TEXT NOT NULL,
                    model_id TEXT NOT NULL,
                    capability TEXT NOT NULL,
                    status TEXT NOT NULL,
                    request_count INTEGER NOT NULL DEFAULT 1,
                    prompt_tokens INTEGER NOT NULL DEFAULT 0,
                    completion_tokens INTEGER NOT NULL DEFAULT 0,
                    image_megabytes REAL NOT NULL DEFAULT 0,
                    latency_ms INTEGER,
                    estimated_cost REAL NOT NULL DEFAULT 0,
                    currency TEXT NOT NULL DEFAULT 'USD',
                    provider_signal TEXT,
                    retry_at TEXT,
                    created_at TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_provider_usage_scope
                    ON provider_usage_events(project_id, created_at);
                CREATE INDEX IF NOT EXISTS idx_provider_usage_provider
                    ON provider_usage_events(provider_id, created_at);
                CREATE TABLE IF NOT EXISTS model_budget_policies (
                    scope_kind TEXT NOT NULL,
                    scope_id TEXT NOT NULL,
                    revision INTEGER NOT NULL DEFAULT 1,
                    timezone TEXT NOT NULL DEFAULT 'Asia/Taipei',
                    policy_json TEXT NOT NULL,
                    effective_from TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    PRIMARY KEY (scope_kind, scope_id),
                    CHECK (scope_kind IN ('global','project'))
                );
                CREATE TABLE IF NOT EXISTS model_budget_reservations (
                    reservation_id TEXT PRIMARY KEY,
                    call_id TEXT NOT NULL UNIQUE,
                    run_id TEXT,
                    project_id TEXT,
                    requests INTEGER NOT NULL,
                    tokens INTEGER NOT NULL,
                    estimated_cost REAL NOT NULL,
                    currency TEXT NOT NULL,
                    status TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    created_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS model_budget_overrides (
                    override_id TEXT PRIMARY KEY,
                    project_id TEXT,
                    run_id TEXT NOT NULL,
                    policy_digest TEXT NOT NULL,
                    status TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    consumed_at TEXT
                );
                CREATE TABLE IF NOT EXISTS model_routing_policies (
                    project_id TEXT PRIMARY KEY,
                    revision INTEGER NOT NULL DEFAULT 1,
                    mode TEXT NOT NULL DEFAULT 'ask',
                    allowed_providers_json TEXT NOT NULL DEFAULT '[]',
                    data_consent_json TEXT NOT NULL DEFAULT '{}',
                    preferred_models_json TEXT NOT NULL DEFAULT '[]',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    CHECK (mode IN ('off','ask','auto_within_policy'))
                );
                CREATE TABLE IF NOT EXISTS model_routing_proposals (
                    proposal_id TEXT PRIMARY KEY,
                    project_id TEXT,
                    run_id TEXT,
                    requested_model TEXT NOT NULL,
                    selected_model TEXT NOT NULL,
                    reason TEXT NOT NULL,
                    requirements_json TEXT NOT NULL,
                    decision_digest TEXT NOT NULL,
                    status TEXT NOT NULL,
                    remember_project INTEGER NOT NULL DEFAULT 0,
                    expires_at TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    consumed_at TEXT
                );
                CREATE TABLE IF NOT EXISTS model_governance_audits (
                    audit_id TEXT PRIMARY KEY,
                    event TEXT NOT NULL,
                    provider_id TEXT,
                    model_id TEXT,
                    project_id TEXT,
                    run_id TEXT,
                    detail_json TEXT NOT NULL,
                    created_at TEXT NOT NULL
                );
                """
            )
            now = _iso(self.clock())
            expired_proposals = conn.execute(
                "UPDATE model_routing_proposals SET status='expired' WHERE status IN ('pending','approved')",
            ).rowcount
            expired_overrides = conn.execute(
                "UPDATE model_budget_overrides SET status='expired' WHERE status IN ('pending','approved')",
            ).rowcount
            conn.execute(
                "UPDATE model_budget_reservations SET status='expired' WHERE status='pending' AND expires_at<=?",
                (now,),
            )
        return {"routing_proposals": expired_proposals, "budget_overrides": expired_overrides}

    def audit(self, event: str, *, provider_id: str = "", model_id: str = "", project_id: Optional[str] = None, run_id: Optional[str] = None, detail: Optional[Mapping[str, Any]] = None) -> None:
        safe_detail = {}
        for key, value in dict(detail or {}).items():
            if any(token in str(key).casefold() for token in ("key", "token", "secret", "authorization", "payload")):
                continue
            safe_detail[str(key)[:80]] = str(value)[:500] if not isinstance(value, (bool, int, float, type(None))) else value
        with self.database.get_db_conn() as conn:
            conn.execute(
                "INSERT INTO model_governance_audits VALUES(?,?,?,?,?,?,?,?)",
                (f"mga_{uuid.uuid4().hex}", str(event)[:80], str(provider_id)[:48] or None,
                 str(model_id)[:200] or None, project_id, run_id, _json(safe_detail), _iso(self.clock())),
            )

    def rotate_credential(self, provider_id: str, credential_version_id: str = "") -> dict[str, Any]:
        provider = _clean_id(provider_id, maximum=48).casefold()
        now = _iso(self.clock())
        version = str(credential_version_id or f"cred_{uuid.uuid4().hex}")
        if not version.startswith("cred_") or len(version) > 80:
            raise ValueError("credential version is invalid")
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO provider_credential_metadata
                   (provider_id,credential_version_id,expires_at,expiry_source,never_expires,last_verified_at,created_at,updated_at)
                   VALUES(?,?,NULL,'unknown',0,NULL,?,?)
                   ON CONFLICT(provider_id) DO UPDATE SET credential_version_id=excluded.credential_version_id,
                   expires_at=NULL,expiry_source='unknown',never_expires=0,last_verified_at=NULL,updated_at=excluded.updated_at""",
                (provider, version, now, now),
            )
            conn.execute("DELETE FROM provider_operational_states WHERE provider_id=?", (provider,))
        self.audit("credential_rotated", provider_id=provider)
        return self.credential_metadata(provider)

    def clear_credential(self, provider_id: str) -> None:
        """Remove live credential metadata without erasing historical usage/audit."""
        provider = _clean_id(provider_id, maximum=48).casefold()
        with self.database.get_db_conn() as conn:
            conn.execute("DELETE FROM provider_operational_states WHERE provider_id=?", (provider,))
            conn.execute("DELETE FROM provider_credential_metadata WHERE provider_id=?", (provider,))
        self.audit("credential_removed", provider_id=provider)

    def credential_metadata(self, provider_id: str) -> dict[str, Any]:
        provider = _clean_id(provider_id, maximum=48).casefold()
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM provider_credential_metadata WHERE provider_id=?", (provider,)).fetchone()
        if row is None:
            return {"provider_id": provider, "credential_version_id": "", "expires_at": None, "expiry_source": "unknown", "never_expires": False, "last_verified_at": None, "remaining_days": None}
        result = dict(row)
        result["never_expires"] = bool(result["never_expires"])
        expiry = None if result["never_expires"] else _parse_time(result.get("expires_at"))
        result["remaining_days"] = None if expiry is None else max(0, math.ceil((expiry - self.clock()).total_seconds() / 86400))
        return result

    def set_credential_metadata(self, provider_id: str, *, expires_at: Optional[str], expiry_source: str, never_expires: bool) -> dict[str, Any]:
        provider = _clean_id(provider_id, maximum=48).casefold()
        source = str(expiry_source or "unknown").casefold()
        if source not in EXPIRY_SOURCES:
            raise GovernanceError("INVALID_EXPIRY_SOURCE", "expiry_source is invalid", status_code=422)
        parsed = None if never_expires or not expires_at else _parse_time(expires_at)
        if expires_at and parsed is None:
            raise GovernanceError("INVALID_EXPIRY_DATE", "expires_at must be an RFC 3339 timestamp", status_code=422)
        current = self.credential_metadata(provider)
        version = current.get("credential_version_id") or f"cred_{uuid.uuid4().hex}"
        now = _iso(self.clock())
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO provider_credential_metadata
                   (provider_id,credential_version_id,expires_at,expiry_source,never_expires,last_verified_at,created_at,updated_at)
                   VALUES(?,?,?,?,?,NULL,?,?)
                   ON CONFLICT(provider_id) DO UPDATE SET expires_at=excluded.expires_at,
                   expiry_source=excluded.expiry_source,never_expires=excluded.never_expires,updated_at=excluded.updated_at""",
                (provider, version, _iso(parsed) if parsed else None, source, int(bool(never_expires)), now, now),
            )
        self.audit("credential_metadata_updated", provider_id=provider, detail={"expiry_source": source, "never_expires": bool(never_expires)})
        return self.credential_metadata(provider)

    def _credential_version(self, provider_id: str) -> str:
        value = self.credential_metadata(provider_id).get("credential_version_id")
        return str(value or "unversioned")

    def mark_verified(self, provider_id: str, *, model_id: str = "", endpoint: str = "") -> dict[str, Any]:
        provider = _clean_id(provider_id, maximum=48).casefold()
        now = _iso(self.clock())
        metadata = self.credential_metadata(provider)
        if metadata.get("credential_version_id"):
            with self.database.get_db_conn() as conn:
                conn.execute("UPDATE provider_credential_metadata SET last_verified_at=?,updated_at=? WHERE provider_id=?", (now, now, provider))
        return self.observe_success(provider, model_id=model_id, endpoint=endpoint)

    def _state_key(self, provider_id: str, model_id: str, endpoint: str) -> tuple[str, str, str]:
        return (_clean_id(provider_id, maximum=48).casefold(), str(model_id or "")[:200], endpoint_fingerprint(endpoint))

    def state(self, provider_id: str, *, model_id: str = "", endpoint: str = "") -> dict[str, Any]:
        key = self._state_key(provider_id, model_id, endpoint)
        with self.database.get_db_conn() as conn:
            row = conn.execute(
                "SELECT * FROM provider_operational_states WHERE provider_id=? AND model_id=? AND endpoint_sha256=?",
                key,
            ).fetchone()
        if row is None and model_id:
            with self.database.get_db_conn() as conn:
                row = conn.execute(
                    "SELECT * FROM provider_operational_states WHERE provider_id=? AND model_id='' AND endpoint_sha256=?",
                    (key[0], key[2]),
                ).fetchone()
        return dict(row) if row else {"provider_id": key[0], "model_id": key[1], "endpoint_sha256": key[2], "state": "unknown", "failure_streak": 0}

    def observe_success(self, provider_id: str, *, model_id: str = "", endpoint: str = "") -> dict[str, Any]:
        key = self._state_key(provider_id, model_id, endpoint)
        now = _iso(self.clock())
        prior = self.state(*key[:1], model_id=key[1], endpoint=endpoint)
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO provider_operational_states
                   (provider_id,model_id,endpoint_sha256,credential_version_id,state,last_success_at,failure_streak,updated_at)
                   VALUES(?,?,?,?, 'healthy',?,0,?)
                   ON CONFLICT(provider_id,model_id,endpoint_sha256) DO UPDATE SET
                   credential_version_id=excluded.credential_version_id,state='healthy',reason_code=NULL,reason=NULL,
                   last_success_at=excluded.last_success_at,failure_streak=0,cooldown_until=NULL,retry_at=NULL,
                   half_open_claimed_at=NULL,updated_at=excluded.updated_at""",
                (*key, self._credential_version(key[0]), now, now),
            )
        recovered_from = str(prior.get("state") or "")
        if recovered_from not in {"", "unknown", "healthy"}:
            self.audit("provider_recovered", provider_id=key[0], model_id=key[1], detail={"prior_state": prior.get("state")})
        result = self.state(key[0], model_id=key[1], endpoint=endpoint)
        if recovered_from not in {"", "unknown", "healthy"}:
            result["recovered_from"] = recovered_from
        return result

    def observe_failure(self, provider_id: str, *, model_id: str = "", endpoint: str = "", status_code: int = 0, retry_after: Any = None, transport_error: bool = False, capability: str = "chat") -> dict[str, Any]:
        provider, requested_model, endpoint_sha = self._state_key(provider_id, model_id, endpoint)
        status = int(status_code or 0)
        prior = self.state(provider, model_id=requested_model, endpoint=endpoint)
        streak = int(prior.get("failure_streak") or 0) + 1
        now_dt = self.clock()
        retry_dt = parse_retry_after(retry_after, now=now_dt)
        target_model = requested_model
        reason_code = f"HTTP_{status}" if status else "TRANSPORT_ERROR"
        if status == 401:
            state = "auth_required"; target_model = ""
        elif status == 402:
            state = "quota_exhausted"; target_model = ""
        elif status == 403:
            state = "permission_denied"
        elif status == 404:
            state = "model_unavailable"
        elif status == 429:
            state = "rate_limited"
            retry_dt = retry_dt or now_dt + timedelta(seconds=min(900, 30 * (2 ** min(5, streak - 1))))
        elif status == 503 and capability == "ocr":
            state = "degraded"
            retry_dt = retry_dt or now_dt + timedelta(seconds=min(900, 30 * (2 ** min(5, streak - 1))))
        elif status >= 500 or transport_error:
            state = "unreachable" if streak >= 3 else "degraded"
            retry_dt = retry_dt or now_dt + timedelta(seconds=min(900, 30 * (2 ** min(5, streak - 1))))
        else:
            state = "degraded"
        if state not in STATES:
            state = "degraded"
        key = (provider, target_model, endpoint_sha)
        now = _iso(now_dt)
        retry_text = _iso(retry_dt) if retry_dt else None
        reason = {
            "auth_required": "API credential is invalid, expired, or revoked.",
            "permission_denied": "This credential is not authorized for the requested model.",
            "quota_exhausted": "Provider credit or billing is unavailable.",
            "rate_limited": "Provider rate limit is active.",
            "model_unavailable": "The requested model is unavailable.",
            "unreachable": "Provider circuit is temporarily open.",
            "degraded": "Provider is temporarily degraded.",
        }[state]
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO provider_operational_states
                   (provider_id,model_id,endpoint_sha256,credential_version_id,state,reason_code,reason,last_failure_at,
                    failure_streak,cooldown_until,retry_at,updated_at)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(provider_id,model_id,endpoint_sha256) DO UPDATE SET
                   credential_version_id=excluded.credential_version_id,state=excluded.state,reason_code=excluded.reason_code,
                   reason=excluded.reason,last_failure_at=excluded.last_failure_at,failure_streak=excluded.failure_streak,
                   cooldown_until=excluded.cooldown_until,retry_at=excluded.retry_at,half_open_claimed_at=NULL,
                   updated_at=excluded.updated_at""",
                (*key, self._credential_version(provider), state, reason_code, reason, now, streak, retry_text, retry_text, now),
            )
        self.audit("provider_suspended", provider_id=provider, model_id=target_model, detail={"state": state, "reason_code": reason_code, "retry_at": retry_text})
        return self.state(provider, model_id=target_model, endpoint=endpoint)

    def operational_decision(self, provider_id: str, *, model_id: str = "", endpoint: str = "", claim_half_open: bool = True) -> GovernanceDecision:
        metadata = self.credential_metadata(provider_id)
        expiry = None if metadata.get("never_expires") else _parse_time(metadata.get("expires_at"))
        if expiry and expiry <= self.clock():
            return GovernanceDecision(False, "PROVIDER_CREDENTIAL_EXPIRED", "API Key 已到期，請更新並完成驗證。")
        state = self.state(provider_id, model_id=model_id, endpoint=endpoint)
        current = str(state.get("state") or "unknown")
        retry = _parse_time(state.get("retry_at"))
        if current in BLOCKING_STATES:
            return GovernanceDecision(False, f"PROVIDER_{current.upper()}", str(state.get("reason") or "Provider route is unavailable."), state.get("retry_at"))
        if current in {"rate_limited", "unreachable", "degraded"} and retry and retry > self.clock():
            return GovernanceDecision(False, "PROVIDER_COOLDOWN", str(state.get("reason") or "Provider is cooling down."), _iso(retry))
        if current in {"rate_limited", "unreachable", "degraded"} and retry and claim_half_open:
            # After cooldown, exactly one request may probe the route.  Its
            # success/failure clears the claim through observe_*.
            claimed = _iso(self.clock())
            with self.database.get_db_conn() as conn:
                changed = conn.execute(
                    """UPDATE provider_operational_states SET half_open_claimed_at=?,updated_at=?
                       WHERE provider_id=? AND model_id=? AND endpoint_sha256=?
                         AND half_open_claimed_at IS NULL""",
                    (
                        claimed,
                        claimed,
                        state["provider_id"],
                        state["model_id"],
                        state["endpoint_sha256"],
                    ),
                ).rowcount
            if not changed:
                return GovernanceDecision(
                    False,
                    "PROVIDER_HALF_OPEN",
                    "Provider 正在進行單次恢復探測，請稍候。",
                    _iso(self.clock() + timedelta(seconds=30)),
                )
        return GovernanceDecision(True)

    @staticmethod
    def _normalize_budget_policy(value: Mapping[str, Any]) -> dict[str, Any]:
        result: dict[str, Any] = {"daily": {}, "monthly": {}}
        for period in ("daily", "monthly"):
            raw = value.get(period) if isinstance(value, Mapping) else None
            if not isinstance(raw, Mapping):
                continue
            for metric in ("requests", "tokens", "cost"):
                limit = raw.get(metric)
                if limit in (None, "", 0, 0.0):
                    continue
                try:
                    amount = float(limit)
                except (TypeError, ValueError) as exc:
                    raise GovernanceError("INVALID_BUDGET", f"{period}.{metric} must be numeric", status_code=422) from exc
                if not math.isfinite(amount) or amount <= 0:
                    raise GovernanceError("INVALID_BUDGET", f"{period}.{metric} must be positive", status_code=422)
                result[period][metric] = int(amount) if metric != "cost" else round(amount, 8)
            currency = str(raw.get("currency") or "USD").strip().upper()[:8]
            result[period]["currency"] = currency or "USD"
        result["warning_thresholds"] = [0.7, 0.9, 1.0]
        result["hard_stop"] = True
        return result

    def get_budget(self, scope_kind: str, scope_id: str) -> dict[str, Any]:
        kind = str(scope_kind or "").casefold()
        identity = "global" if kind == "global" else _clean_id(scope_id, maximum=128)
        if kind not in {"global", "project"}:
            raise GovernanceError("INVALID_BUDGET_SCOPE", "Budget scope must be global or project", status_code=422)
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM model_budget_policies WHERE scope_kind=? AND scope_id=?", (kind, identity)).fetchone()
        if row is None:
            return {"scope_kind": kind, "scope_id": identity, "revision": 0, "timezone": "Asia/Taipei", "policy": {"daily": {}, "monthly": {}, "warning_thresholds": [0.7, 0.9, 1.0], "hard_stop": True}, "effective_from": None}
        result = dict(row); result["policy"] = _loads(result.pop("policy_json"), {})
        return result

    def put_budget(self, scope_kind: str, scope_id: str, *, revision: int, timezone_name: str, policy: Mapping[str, Any]) -> dict[str, Any]:
        current = self.get_budget(scope_kind, scope_id)
        if int(revision) != int(current["revision"]):
            raise GovernanceError("BUDGET_REVISION_CONFLICT", "Budget changed; reload before saving.", status_code=409)
        try:
            ZoneInfo(str(timezone_name or "Asia/Taipei"))
        except Exception as exc:
            raise GovernanceError("INVALID_TIMEZONE", "Budget timezone is invalid", status_code=422) from exc
        normalized = self._normalize_budget_policy(policy)
        now = _iso(self.clock()); next_revision = int(current["revision"]) + 1
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO model_budget_policies(scope_kind,scope_id,revision,timezone,policy_json,effective_from,created_at,updated_at)
                   VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(scope_kind,scope_id) DO UPDATE SET revision=excluded.revision,
                   timezone=excluded.timezone,policy_json=excluded.policy_json,effective_from=excluded.effective_from,updated_at=excluded.updated_at""",
                (current["scope_kind"], current["scope_id"], next_revision, timezone_name, _json(normalized), now, now, now),
            )
        self.audit("budget_updated", project_id=current["scope_id"] if current["scope_kind"] == "project" else None, detail={"scope": current["scope_kind"], "revision": next_revision})
        return self.get_budget(scope_kind, scope_id)

    @staticmethod
    def _period_start(period: str, tz_name: str, now: datetime) -> str:
        local = now.astimezone(ZoneInfo(tz_name))
        if period == "daily":
            start = local.replace(hour=0, minute=0, second=0, microsecond=0)
        else:
            start = local.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        return start.astimezone(timezone.utc).isoformat()

    def _usage_since(self, *, project_id: Optional[str], since: str, currency: str) -> dict[str, float]:
        clauses = ["created_at>=?"]; params: list[Any] = [since]
        if project_id is not None:
            clauses.append("project_id=?"); params.append(project_id)
        now = _iso(self.clock())
        reservation_clauses = ["created_at>=?", "status='pending'", "expires_at>?"]
        reservation_params: list[Any] = [since, now]
        if project_id is not None:
            reservation_clauses.append("project_id=?")
            reservation_params.append(project_id)
        with self.database.get_db_conn() as conn:
            row = conn.execute(
                f"""SELECT COALESCE(SUM(request_count),0) requests,
                    COALESCE(SUM(prompt_tokens+completion_tokens),0) tokens,
                    COALESCE(SUM(CASE WHEN currency=? THEN estimated_cost ELSE 0 END),0) cost
                    FROM provider_usage_events WHERE {' AND '.join(clauses)}""",
                [currency, *params],
            ).fetchone()
            pending = conn.execute(
                f"""SELECT COALESCE(SUM(requests),0) requests,
                    COALESCE(SUM(tokens),0) tokens,
                    COALESCE(SUM(CASE WHEN currency=? THEN estimated_cost ELSE 0 END),0) cost
                    FROM model_budget_reservations WHERE {' AND '.join(reservation_clauses)}""",
                [currency, *reservation_params],
            ).fetchone()
        return {
            "requests": float(row["requests"]) + float(pending["requests"]),
            "tokens": float(row["tokens"]) + float(pending["tokens"]),
            "cost": float(row["cost"]) + float(pending["cost"]),
        }

    def budget_decision(self, *, project_id: Optional[str], run_id: str, call_id: str, reserve_tokens: int = 0, reserve_cost: float = 0, currency: str = "USD", override_id: Optional[str] = None) -> GovernanceDecision:
        with self._lock:
            return self._budget_decision_locked(
                project_id=project_id,
                run_id=run_id,
                call_id=call_id,
                reserve_tokens=reserve_tokens,
                reserve_cost=reserve_cost,
                currency=currency,
                override_id=override_id,
            )

    def _budget_decision_locked(self, *, project_id: Optional[str], run_id: str, call_id: str, reserve_tokens: int = 0, reserve_cost: float = 0, currency: str = "USD", override_id: Optional[str] = None) -> GovernanceDecision:
        if override_id and self.consume_budget_override(override_id, project_id=project_id, run_id=run_id):
            return GovernanceDecision(True)
        warnings: list[dict[str, Any]] = []
        policies = [self.get_budget("global", "global")]
        if project_id:
            policies.append(self.get_budget("project", project_id))
        now = self.clock()
        blocking = None
        for record in policies:
            if int(record.get("revision") or 0) <= 0:
                continue
            for period in ("daily", "monthly"):
                limits = (record.get("policy") or {}).get(period) or {}
                observed = self._usage_since(
                    project_id=project_id if record["scope_kind"] == "project" else None,
                    since=self._period_start(period, record["timezone"], now),
                    currency=str(limits.get("currency") or currency).upper(),
                )
                projected = {"requests": observed["requests"] + 1, "tokens": observed["tokens"] + max(0, reserve_tokens), "cost": observed["cost"] + max(0.0, reserve_cost)}
                for metric in ("requests", "tokens", "cost"):
                    limit = limits.get(metric)
                    if not limit:
                        continue
                    ratio = projected[metric] / float(limit)
                    if ratio >= 0.7:
                        warnings.append({"scope": record["scope_kind"], "period": period, "metric": metric, "ratio": round(ratio, 4), "limit": limit})
                    if ratio >= 1:
                        blocking = warnings[-1]
        if blocking:
            return GovernanceDecision(False, "MODEL_BUDGET_EXCEEDED", "模型用量已達預算上限。", warnings=tuple(warnings))
        reservation = f"mbr_{uuid.uuid4().hex}"
        with self.database.get_db_conn() as conn:
            conn.execute(
                "INSERT OR IGNORE INTO model_budget_reservations VALUES(?,?,?,?,?,?,?,?,?,?,?)",
                (reservation, call_id, run_id, project_id, 1, max(0, reserve_tokens), max(0.0, reserve_cost), str(currency).upper()[:8], "pending", _iso(now + timedelta(minutes=15)), _iso(now)),
            )
        return GovernanceDecision(True, warnings=tuple(warnings), reservation_id=reservation)

    def record_usage(self, *, call_id: str, provider_id: str, model_id: str, capability: str, project_id: Optional[str] = None, run_id: Optional[str] = None, status: str = "completed", prompt_tokens: int = 0, completion_tokens: int = 0, image_megabytes: float = 0, latency_ms: Optional[int] = None, estimated_cost: float = 0, currency: str = "USD", provider_signal: str = "", retry_at: Optional[str] = None) -> None:
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT OR IGNORE INTO provider_usage_events
                   (call_id,run_id,project_id,provider_id,model_id,capability,status,request_count,prompt_tokens,completion_tokens,
                    image_megabytes,latency_ms,estimated_cost,currency,provider_signal,retry_at,created_at)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (_clean_id(call_id, maximum=160), run_id, project_id, str(provider_id)[:48], str(model_id)[:200], str(capability)[:40], str(status)[:32], 1,
                 max(0, int(prompt_tokens or 0)), max(0, int(completion_tokens or 0)), max(0.0, float(image_megabytes or 0)),
                 None if latency_ms is None else max(0, int(latency_ms)), max(0.0, float(estimated_cost or 0)), str(currency or "USD").upper()[:8],
                 str(provider_signal or "")[:80] or None, retry_at, _iso(self.clock())),
            )
            conn.execute("UPDATE model_budget_reservations SET status='reconciled' WHERE call_id=?", (call_id,))

    def usage(self, *, project_id: Optional[str] = None, since: Optional[str] = None) -> dict[str, Any]:
        clauses = ["1=1"]; params: list[Any] = []
        if project_id:
            clauses.append("project_id=?"); params.append(project_id)
        if since:
            clauses.append("created_at>=?"); params.append(since)
        with self.database.get_db_conn() as conn:
            rows = conn.execute(f"SELECT * FROM provider_usage_events WHERE {' AND '.join(clauses)} ORDER BY created_at DESC", params).fetchall()
        totals = {"requests": 0, "prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0, "image_megabytes": 0.0}
        costs: dict[str, float] = {}; by_provider: dict[str, dict[str, Any]] = {}
        for raw in rows:
            row = dict(raw); provider = row["provider_id"]
            bucket = by_provider.setdefault(provider, {"requests": 0, "tokens": 0, "errors": 0, "image_megabytes": 0.0})
            totals["requests"] += int(row["request_count"]); totals["prompt_tokens"] += int(row["prompt_tokens"]); totals["completion_tokens"] += int(row["completion_tokens"])
            totals["image_megabytes"] += float(row["image_megabytes"]); bucket["requests"] += int(row["request_count"]); bucket["tokens"] += int(row["prompt_tokens"]) + int(row["completion_tokens"]); bucket["image_megabytes"] += float(row["image_megabytes"])
            if row["status"] != "completed": bucket["errors"] += 1
            costs[row["currency"]] = costs.get(row["currency"], 0.0) + float(row["estimated_cost"])
        totals["total_tokens"] = totals["prompt_tokens"] + totals["completion_tokens"]
        historical = self.database.get_usage_ledger(project_id=project_id, since=since)
        return {
            "totals": totals,
            "cost_by_currency": {k: round(v, 8) for k, v in costs.items()},
            "by_provider": by_provider,
            "source": "local_observation",
            "events": [dict(row) for row in rows[:100]],
            # Existing Run metrics remain report-only. Budget evaluation reads
            # provider_usage_events after policy effective_from and never this.
            "historical_runs": {**historical, "budget_eligible": False},
        }

    def get_routing_policy(self, project_id: str) -> dict[str, Any]:
        project = _clean_id(project_id, maximum=128)
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM model_routing_policies WHERE project_id=?", (project,)).fetchone()
        if row is None:
            return {"project_id": project, "revision": 0, "mode": "ask", "allowed_providers": [], "data_consent": {"text": False, "images": False, "documents": False}, "preferred_models": []}
        result = dict(row); result["allowed_providers"] = _loads(result.pop("allowed_providers_json"), []); result["data_consent"] = _loads(result.pop("data_consent_json"), {}); result["preferred_models"] = _loads(result.pop("preferred_models_json"), [])
        return result

    def put_routing_policy(self, project_id: str, *, revision: int, mode: str, allowed_providers: Iterable[str], data_consent: Mapping[str, Any], preferred_models: Iterable[str]) -> dict[str, Any]:
        current = self.get_routing_policy(project_id); normalized_mode = str(mode or "ask").casefold()
        if normalized_mode not in ROUTING_MODES:
            raise GovernanceError("INVALID_ROUTING_MODE", "Routing mode is invalid", status_code=422)
        if int(revision) != int(current["revision"]):
            raise GovernanceError("ROUTING_REVISION_CONFLICT", "Routing policy changed; reload before saving.", status_code=409)
        providers = sorted({_clean_id(item, maximum=48).casefold() for item in allowed_providers})[:32]
        consent = {key: bool(data_consent.get(key, False)) for key in ("text", "images", "documents")}
        models = [str(item)[:240] for item in preferred_models if str(item).strip()][:64]
        now = _iso(self.clock()); next_revision = int(current["revision"]) + 1
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO model_routing_policies VALUES(?,?,?,?,?,?,?,?)
                   ON CONFLICT(project_id) DO UPDATE SET revision=excluded.revision,mode=excluded.mode,
                   allowed_providers_json=excluded.allowed_providers_json,data_consent_json=excluded.data_consent_json,
                   preferred_models_json=excluded.preferred_models_json,updated_at=excluded.updated_at""",
                (project_id, next_revision, normalized_mode, _json(providers), _json(consent), _json(models), now, now),
            )
        self.audit("routing_policy_updated", project_id=project_id, detail={"mode": normalized_mode, "revision": next_revision})
        return self.get_routing_policy(project_id)

    def resolve_route(self, *, project_id: Optional[str], run_id: Optional[str], requested_model: str, requirements: Mapping[str, Any], candidates: Iterable[Mapping[str, Any]]) -> dict[str, Any]:
        required_kind = str(requirements.get("kind") or "chat").casefold()
        needs_tools = bool(requirements.get("tools")); data_types = {key for key in ("text", "images", "documents") if requirements.get(key)}
        policy = self.get_routing_policy(project_id) if project_id else {"mode": "ask", "allowed_providers": [], "data_consent": {}}
        valid = []
        for raw in candidates:
            item = dict(raw); profile = item.get("profile") if isinstance(item.get("profile"), Mapping) else {}
            if required_kind == "chat" and not profile.get("supports_chat"):
                continue
            if needs_tools and not profile.get("supports_tools"):
                continue
            provider = str(item.get("provider") or "ollama").casefold(); model = str(item.get("name") or item.get("model") or "")
            provider_model = model.split("::", 1)[1] if "::" in model else model
            if not model or not self.operational_decision(
                provider,
                model_id=provider_model,
                endpoint=str(item.get("endpoint") or ""),
                claim_half_open=False,
            ).allowed:
                continue
            item["provider"] = provider; item["model"] = model
            valid.append(item)
        if not valid:
            raise GovernanceError("NO_SUITABLE_MODEL", "沒有符合能力、健康與專案政策的模型。", status_code=409)
        valid.sort(key=lambda item: (
            0 if item["model"] == requested_model else 1,
            0 if item["provider"] == "ollama" else 1,
            float(item.get("estimated_cost") or 0),
            item["model"],
        ))
        selected = valid[0]
        if selected["model"] == requested_model:
            return {"status": "selected", "model": requested_model, "provider": selected["provider"], "reason": "requested_model_satisfies_policy"}
        provider_allowed = selected["provider"] == "ollama" or selected["provider"] in set(policy.get("allowed_providers") or [])
        data_allowed = all(bool((policy.get("data_consent") or {}).get(kind)) for kind in data_types if selected["provider"] != "ollama")
        can_auto = policy.get("mode") == "auto_within_policy" and provider_allowed and data_allowed
        if can_auto:
            self.audit("model_routed", provider_id=selected["provider"], model_id=selected["model"], project_id=project_id, run_id=run_id, detail={"from": requested_model, "reason": "project_policy"})
            return {"status": "selected", "model": selected["model"], "provider": selected["provider"], "reason": "project_policy"}
        if policy.get("mode") == "off":
            raise GovernanceError("MODEL_CAPABILITY_MISMATCH", "目前模型不適合這項工作，且自動選模已關閉。", status_code=409)
        proposal_id = f"mrp_{uuid.uuid4().hex}"; expires = self.clock() + timedelta(minutes=10)
        digest_payload = {"project_id": project_id, "requested_model": requested_model, "selected_model": selected["model"], "requirements": dict(requirements), "policy_revision": policy.get("revision", 0)}
        digest = hashlib.sha256(_json(digest_payload).encode()).hexdigest()
        with self.database.get_db_conn() as conn:
            conn.execute(
                """INSERT INTO model_routing_proposals
                   (proposal_id,project_id,run_id,requested_model,selected_model,reason,requirements_json,
                    decision_digest,status,remember_project,expires_at,created_at,consumed_at)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NULL)""",
                (proposal_id, project_id, run_id, requested_model, selected["model"], "required_capability", _json(dict(requirements)), digest, "pending", 0, _iso(expires), _iso(self.clock())),
            )
        return {"status": "approval_required", "event": "model_route_proposed", "proposal_id": proposal_id, "requested_model": requested_model, "selected_model": selected["model"], "provider": selected["provider"], "reason": "required_capability", "expires_at": _iso(expires)}

    def approve_proposal(self, proposal_id: str, *, remember_project: bool) -> dict[str, Any]:
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM model_routing_proposals WHERE proposal_id=?", (proposal_id,)).fetchone()
            if row is None or row["status"] != "pending" or (_parse_time(row["expires_at"]) or self.clock()) <= self.clock():
                raise GovernanceError("ROUTING_PROPOSAL_INVALID", "Routing proposal is missing, expired, or already used.", status_code=409)
            conn.execute("UPDATE model_routing_proposals SET status='approved',remember_project=? WHERE proposal_id=?", (int(bool(remember_project)), proposal_id))
        if remember_project and row["project_id"]:
            policy = self.get_routing_policy(str(row["project_id"]))
            provider = str(row["selected_model"]).split("::", 1)[0].casefold() if "::" in str(row["selected_model"]) else "ollama"
            requirements = _loads(row["requirements_json"], {})
            allowed = set(policy.get("allowed_providers") or [])
            if provider != "ollama":
                allowed.add(provider)
            consent = dict(policy.get("data_consent") or {})
            for key in ("text", "images", "documents"):
                if requirements.get(key):
                    consent[key] = True
            self.put_routing_policy(
                str(row["project_id"]),
                revision=int(policy["revision"]),
                mode="auto_within_policy",
                allowed_providers=allowed,
                data_consent=consent,
                preferred_models=[str(row["selected_model"]), *(policy.get("preferred_models") or [])],
            )
        return {**dict(row), "status": "approved", "remember_project": bool(remember_project)}

    def consume_proposal(self, proposal_id: str, *, project_id: Optional[str], requested_model: str) -> Optional[str]:
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM model_routing_proposals WHERE proposal_id=?", (proposal_id,)).fetchone()
            if row is None or row["status"] != "approved" or row["project_id"] != project_id or row["requested_model"] != requested_model or (_parse_time(row["expires_at"]) or self.clock()) <= self.clock():
                return None
            conn.execute("UPDATE model_routing_proposals SET status='consumed',consumed_at=? WHERE proposal_id=?", (_iso(self.clock()), proposal_id))
        return str(row["selected_model"])

    def create_budget_override(self, *, project_id: Optional[str], run_id: str) -> dict[str, Any]:
        policies = [self.get_budget("global", "global")]
        if project_id: policies.append(self.get_budget("project", project_id))
        digest = hashlib.sha256(_json([{"scope": p["scope_kind"], "id": p["scope_id"], "revision": p["revision"]} for p in policies]).encode()).hexdigest()
        override_id = f"mbo_{uuid.uuid4().hex}"; expires = self.clock() + timedelta(minutes=10)
        with self.database.get_db_conn() as conn:
            conn.execute("INSERT INTO model_budget_overrides VALUES(?,?,?,?,?,?,?,NULL)", (override_id, project_id, run_id, digest, "approved", _iso(expires), _iso(self.clock())))
        return {"override_id": override_id, "project_id": project_id, "run_id": run_id, "expires_at": _iso(expires)}

    def consume_budget_override(self, override_id: str, *, project_id: Optional[str], run_id: str) -> bool:
        with self.database.get_db_conn() as conn:
            row = conn.execute("SELECT * FROM model_budget_overrides WHERE override_id=?", (override_id,)).fetchone()
            if row is None or row["status"] != "approved" or row["project_id"] != project_id or row["run_id"] != run_id or (_parse_time(row["expires_at"]) or self.clock()) <= self.clock():
                return False
            conn.execute("UPDATE model_budget_overrides SET status='consumed',consumed_at=? WHERE override_id=?", (_iso(self.clock()), override_id))
        return True

    def overview(self, *, project_id: Optional[str], providers: Iterable[Mapping[str, Any]]) -> dict[str, Any]:
        items = []
        for raw in providers:
            provider = str(raw.get("id") or "").casefold(); model = str(raw.get("selected_model") or ""); endpoint = str(raw.get("base_url") or "")
            if not provider: continue
            items.append({"provider_id": provider, "model_id": model, "enabled": raw.get("enabled") is True, "credential": self.credential_metadata(provider), "operational": self.state(provider, model_id=model, endpoint=endpoint)})
        since = _iso(self.clock() - timedelta(days=30))
        return {"providers": items, "usage": self.usage(project_id=project_id, since=since), "global_budget": self.get_budget("global", "global"), "project_budget": self.get_budget("project", project_id) if project_id else None, "routing_policy": self.get_routing_policy(project_id) if project_id else None}


def configure_model_governance(service: Optional[ModelGovernanceService]) -> Optional[ModelGovernanceService]:
    global _SERVICE
    prior = _SERVICE; _SERVICE = service; return prior


def get_model_governance() -> Optional[ModelGovernanceService]:
    return _SERVICE


__all__ = [
    "GovernanceDecision", "GovernanceError", "ModelGovernanceService",
    "configure_model_governance", "endpoint_fingerprint", "get_model_governance",
    "parse_retry_after",
]
