"""Create the reproducible Windows/Python 3.11 dependency lock.

``backend/requirements.txt`` names the intentionally managed top-level
packages.  The lock is generated from pip's fresh ``--ignore-installed``
resolution report so transitive packages cannot drift independently, which is
how docling 2.15 ended up beside an API-incompatible docling-core.

Resolve first:

    python -m pip install --dry-run --ignore-installed \
      --report artifacts/dependency-lock-report.json \
      -r backend/requirements.txt

Then generate:

    python scripts/lock_dependencies.py \
      --report artifacts/dependency-lock-report.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "artifacts" / "dependency-lock-report.json"
DEFAULT_OUTPUT = ROOT / "backend" / "requirements.lock"


def _locked_lines(report: Dict[str, Any]) -> List[str]:
    resolved: Dict[str, str] = {}
    for item in report.get("install", []):
        metadata = item.get("metadata") or {}
        name = str(metadata.get("name") or "").strip()
        version = str(metadata.get("version") or "").strip()
        hashes = ((item.get("download_info") or {}).get("archive_info") or {}).get("hashes") or {}
        sha256 = str(hashes.get("sha256") or "").strip()
        if not (name and version and sha256):
            raise ValueError(f"unlocked resolution entry: {name or item!r}")
        key = name.casefold().replace("_", "-")
        line = f"{name}=={version} --hash=sha256:{sha256}"
        previous = resolved.get(key)
        if previous and previous != line:
            raise ValueError(f"conflicting resolution entries for {name}: {previous!r} / {line!r}")
        resolved[key] = line
    if not resolved:
        raise ValueError("pip report contains no install entries")
    return [resolved[key] for key in sorted(resolved)]


def write_lock(report_path: Path, output_path: Path) -> int:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    environment = report.get("environment") or {}
    python_version = environment.get("python_version", "3.11")
    platform = environment.get("sys_platform", "win32")
    lines = [
        "# Generated by scripts/lock_dependencies.py; do not edit by hand.",
        f"# Target: Python {python_version}, platform {platform}.",
        "# Regenerate from a fresh pip --ignore-installed resolution report.",
        "",
        *_locked_lines(report),
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return len(lines) - 5


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    count = write_lock(args.report, args.output)
    print(f"wrote {count} fully pinned and hashed distributions -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
